version: '2'
networks:
  byfn:
services:

  orderer.bartdigital.com.br:
    container_name: orderer.bartdigital.com.br
    image: hyperledger/fabric-orderer
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # - ORDERER_GENERAL_TLS_ENABLED=true
      # - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      # - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      # - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/smart-contract/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ./crypto-config/ordererOrganizations/bartdigital.com.br/orderers/orderer.bartdigital.com.br/msp:/var/hyperledger/orderer/msp
    - ./crypto-config/ordererOrganizations/bartdigital.com.br/orderers/orderer.bartdigital.com.br/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050
    networks:
      - byfn

  peer0.bart.bartdigital.com.br:
    image: hyperledger/fabric-peer
    container_name: peer0.bart.bartdigital.com.br
    environment:
      - CORE_PEER_ID=peer0.bart.bartdigital.com.br
      - CORE_PEER_ADDRESS=peer0.bart.bartdigital.com.br:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7053
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.bart.bartdigital.com.br:7051
      - CORE_PEER_LOCALMSPID=BartMSP
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_byfn
      - FABRIC_LOGGING_SPEC=DEBUG
      # - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      # - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      # - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      # - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/smart-contract/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/bart.bartdigital.com.br/peers/peer0.bart.bartdigital.com.br/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/bart.bartdigital.com.br/peers/peer0.bart.bartdigital.com.br/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7053:7053
    networks:
      - byfn

  peer0.creditors.bartdigital.com.br:
    image: hyperledger/fabric-peer
    container_name: peer0.creditors.bartdigital.com.br
    environment:
      - CORE_PEER_ID=peer0.creditors.bartdigital.com.br
      - CORE_PEER_ADDRESS=peer0.creditors.bartdigital.com.br:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7053
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.creditors.bartdigital.com.br:7051
      - CORE_PEER_LOCALMSPID=CreditorsMSP
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_byfn
      - FABRIC_LOGGING_SPEC=DEBUG
      # - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      # - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      # - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      # - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/smart-contract/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/:/host/var/run/
      - ./crypto-config/peerOrganizations/creditors.bartdigital.com.br/peers/peer0.creditors.bartdigital.com.br/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/creditors.bartdigital.com.br/peers/peer0.creditors.bartdigital.com.br/tls:/etc/hyperledger/fabric/tls
    ports:
      - 8051:7051
      - 8053:7053
    networks:
      - byfn

  peer0.auditors.bartdigital.com.br:
    image: hyperledger/fabric-peer
    container_name: peer0.auditors.bartdigital.com.br
    environment:
      - CORE_PEER_ID=peer0.auditors.bartdigital.com.br
      - CORE_PEER_ADDRESS=peer0.auditors.bartdigital.com.br:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7053
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.auditors.bartdigital.com.br:7051
      - CORE_PEER_LOCALMSPID=AuditorsMSP
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_byfn
      - FABRIC_LOGGING_SPEC=DEBUG
      # - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      # - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      # - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      # - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/smart-contract/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/auditors.bartdigital.com.br/peers/peer0.auditors.bartdigital.com.br/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/auditors.bartdigital.com.br/peers/peer0.auditors.bartdigital.com.br/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9051:7051
      - 9053:7053
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.bart.bartdigital.com.br:7051
      - CORE_PEER_LOCALMSPID=BartMSP
      # - CORE_PEER_TLS_ENABLED=true
      # - CORE_PEER_TLS_CERT_FILE=/opt/gopath/smart-contract/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/bart.bartdigital.com.br/peers/peer0.bart.bartdigital.com.br/tls/server.crt
      # - CORE_PEER_TLS_KEY_FILE=/opt/gopath/smart-contract/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/bart.bartdigital.com.br/peers/peer0.bart.bartdigital.com.br/tls/server.key
      # - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/smart-contract/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/bart.bartdigital.com.br/peers/peer0.bart.bartdigital.com.br/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/smart-contract/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/bart.bartdigital.com.br/users/Admin@bart.bartdigital.com.br/msp
      # - ORDERER_CA=/opt/gopath/smart-contract/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/bartdigital.com.br/orderers/orderer.bartdigital.com.br/msp/tlscacerts/tlsca.bartdigital.com.br-cert.pem
    working_dir: /opt/gopath/smart-contract/github.com/hyperledger/fabric/peer
    command: /bin/bash #-c 'sleep 1000'
    volumes:
      - /var/run:/host/var/run/
      - ./crypto-config:/opt/gopath/smart-contract/github.com/hyperledger/fabric/peer/crypto/
      - /home/john/www/bart-network/smart-contract/dist:/opt/gopath/smart-contract/github.com/chaincode
      - ./channel-artifacts:/opt/gopath/smart-contract/github.com/hyperledger/fabric/peer/channel-artifacts
    networks:
      - byfn
